### ISSUE TITLE
Green light won't light when local tests pass

### ISSUE THREAD

**Issue by yayitserica** [learn-co-curriculum/swift-arrayChallengeToo-lab#9]
![screen shot 2016-09-05 at 12 45 48 pm](https://cloud.githubusercontent.com/assets/15487798/18253921/be499488-7366-11e6-88c9-3a3178ae0b07.png)

**Comment by AnnJohn** [comment]
hi @yayitserica since this is a technical product issue, could you file a bug report (if you click on your profile pic in Learn, you'll see a dropdown menu with an option to Report a Bug). Since this doesn't prevent you from moving forward in the track, please feel free to continue on with the next lesson. thanks.

**Comment by yayitserica** [comment]
Will do, thanks!
